import exp from "express";
import { add, disp, upd, del } from "./hscontrol.js";
import { checkToken, newUser, login } from "./userscontrols.js";
const method = exp.Router();
method.route("/").get(disp);
method.route("/users/new").post(newUser);
method.route("/users/login").post(login);
method.use(checkToken);
method.route("/:key").put(upd);
method.route("/").delete(del).post(add);
export default method;
